import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createBackendClient} from './backendClient.js'
test('cookie authentication sends CSRF header without exposing a token',async()=>{let options;const c=createBackendClient({cookieAuth:true,fetchImpl:async(_url,input)=>{options=input;return {ok:true,status:200,json:async()=>({})}}});await c.createCase({title:'Synthetic'});assert.equal(options.credentials,'same-origin');assert.equal(options.headers['X-CSRF-Protection'],'1');assert.equal(options.headers.Authorization,undefined)})
test('backend adapter forbids insecure remote origins',()=>assert.throws(()=>createBackendClient({baseUrl:'http://example.org',getToken:()=>''}),/HTTPS/))
test('backend adapter requires identity before sending',async()=>{const c=createBackendClient({getToken:()=>''});await assert.rejects(c.cases(),/identity/)})
test('backend adapter preserves version and scoped URL',async()=>{let call;const c=createBackendClient({getToken:()=> 'test-token',fetchImpl:async(url,options)=>{call={url:String(url),...options};return {ok:true,status:200,json:async()=>({version:2})}}});assert.deepEqual(await c.savePassport('case-a',{facts:{}},7),{version:2});assert.equal(call.url,'http://127.0.0.1:8000/api/v1/cases/case-a/passport/answers');assert.equal(JSON.parse(call.body).expected_revision,7);assert.equal(call.headers.Authorization,'Bearer test-token')})
test('backend adapter exposes stale-write conflict to UI',async()=>{const c=createBackendClient({getToken:()=> 'test',fetchImpl:async()=>({ok:false,status:409,json:async()=>({detail:'Stale revision'})})});await assert.rejects(c.cases(),e=>e.status===409)})
test('backend adapter handles checklist item update and queue methods',async()=>{let call;const c=createBackendClient({getToken:()=> 'test-token',fetchImpl:async(url,options)=>{call={url:String(url),...options};return {ok:true,status:200,json:async()=>({status:'DONE'})}}});const res=await c.updateChecklistItem('chk-1','item-1','DONE',3);assert.deepEqual(res,{status:'DONE'});assert.equal(call.url,'http://127.0.0.1:8000/api/v1/checklists/chk-1/items/item-1');assert.equal(JSON.parse(call.body).status,'DONE');assert.equal(JSON.parse(call.body).expected_revision,3);const queueRes=await c.queue();assert.ok(queueRes)})
