export const sources=[
 {id:'india-code',title:'India Code',authority:'Ministry of Law and Justice',domain:'IP',jurisdiction:'IN',description:'Official legislation portal. Start with statutory text, then review applicable amendments.',url:'https://www.indiacode.nic.in/'},
 {id:'ip-india',title:'IP India',authority:'Office of the CGPDTM',domain:'IP',jurisdiction:'IN',description:'Patent, trademark, design and geographical indication resources and official registries.',url:'https://www.ipindia.gov.in/'},
 {id:'nba',title:'National Biodiversity Authority',authority:'NBA',domain:'ABS',jurisdiction:'IN',description:'Biodiversity notifications, ABS regulations and official access pathways.',url:'https://nbaindia.nic.in/public-information/notification-guidelines'},
 {id:'fssai',title:'Food Safety & Standards Authority',authority:'FSSAI',domain:'Regulatory',jurisdiction:'IN',description:'Official food regulations and Ayurveda Aahara resources. Confirm the applicable version.',url:'https://www.fssai.gov.in/'},
 {id:'cdsco',title:'CDSCO',authority:'Ministry of Health and Family Welfare',domain:'Regulatory',jurisdiction:'IN',description:'Traditional drug definitions and drug-regulatory reference material.',url:'https://www.cdsco.gov.in/opencms/opencms/en/Traditional_Drugs/'},
 {id:'tkdl',title:'Traditional Knowledge Digital Library',authority:'CSIR',domain:'TK',jurisdiction:'IN',description:'A pointer to TKDL. Content access and reuse depend on authorization and terms.',url:'https://www.tkdl.res.in/'},
 {id:'wipo',title:'WIPO treaties & intellectual property',authority:'World Intellectual Property Organization',domain:'IP',jurisdiction:'INTERNATIONAL',description:'International IP frameworks. Country participation and effective dates need separate checks.',url:'https://www.wipo.int/en/web/treaties'},
 {id:'cbd',title:'Convention on Biological Diversity',authority:'CBD Secretariat',domain:'ABS',jurisdiction:'INTERNATIONAL',description:'Convention and Nagoya Protocol resources for jurisdiction-specific research.',url:'https://www.cbd.int/abs/'}
]
export const steps=[
 {name:'Use & claims',hi:'उपयोग और दावे',help:'Your intended claims affect the regulatory questions we need to ask.',fields:[['use','Intended use','उपयोग',['Therapeutic','Food','Cosmetic','Research','Unknown']],['claims','Proposed claims','प्रस्तावित दावे',null,'Describe intended claims. Avoid confidential information.'],['form','Dosage / product form','उत्पाद का रूप',['Capsule','Powder','Liquid','Topical','Other','Unknown']]]},
 {name:'Source & ingredients',hi:'स्रोत और सामग्री',help:'Names and source references are enough at this stage. Exact formulation ratios are not required.',fields:[['source','Authoritative text / formula reference','ग्रंथ या सूत्र संदर्भ',null,'Reference or Unknown'],['ingredients','Ingredients & plant parts','सामग्री और पौधे के भाग',null,'Names and parts, or Unknown'],['origin','Biological-resource origin','जैव संसाधन का मूल',['India','Outside India','Mixed','Unknown']]]},
 {name:'Process & evidence',hi:'प्रक्रिया और प्रमाण',help:'Changes to processing and available evidence may affect the route. No files leave your device in this demo.',fields:[['processing','Processing or formulation changes','प्रक्रिया में बदलाव',null,'Describe the change, or Unknown'],['evidence','Available evidence','उपलब्ध प्रमाण',['Text reference only','Quality testing','Safety / efficacy studies','None yet','Unknown']]]},
 {name:'Applicant & stage',hi:'आवेदक और चरण',help:'Applicant and activity details support a later ABS assessment. Unknown facts will stay unresolved.',fields:[['applicant','Applicant type','आवेदक प्रकार',['Individual','Indian organisation','Foreign organisation','Unknown']],['stage','Development stage','विकास चरण',['Research','Prototype','Preparing launch','Commercial','Unknown']]]},
 {name:'Market & disclosure',hi:'बाजार और प्रकाशन',help:'A market choice does not establish approval. Publication and disclosure questions need expert review.',fields:[['market','Intended market','लक्षित बाजार',['India','United States','European Union','Other','Unknown']],['disclosure','Public disclosure or filing','सार्वजनिक प्रकटीकरण',['Not disclosed','Published / shared publicly','Application filed','Unknown']]]}
]
