import { useState } from 'react'
import { useApp } from './context'
import { validateIngredient } from './passportRules'
const blank=()=>({id:crypto.randomUUID(),name:'',part:'Unknown',kind:'Unknown',origin:'Unknown',sourcing:'Unknown',provenance:'user-entered'})
export default function IngredientEditor({rows=[],onChange}){
 const {language}=useApp(),hi=language==='hi',t=(a,b)=>hi?b:a
 const [draft,setDraft]=useState(null),[page,setPage]=useState(0),[error,setError]=useState('')
 const fields=page===0?[['name','Ingredient name','सामग्री का नाम',null],['kind','Biological type','जैविक प्रकार',['Plant','Animal','Microbial','Non-biological','Unknown']],['part','Part / material used','प्रयुक्त भाग',null]]:[['origin','Origin','मूल',['India','Outside India','Mixed','Unknown']],['sourcing','Sourcing','स्रोत',['Cultivated','Wild collected','Purchased','Unknown']]]
 const labels={Plant:'पौधा',Animal:'पशु',Microbial:'सूक्ष्मजीव','Non-biological':'गैर-जैविक',Unknown:'अज्ञात',India:'भारत','Outside India':'भारत से बाहर',Mixed:'मिश्रित',Cultivated:'कृषि से', 'Wild collected':'वन से संग्रह',Purchased:'खरीदा गया'}
 return <div className="ingredient-editor"><p>{t('Keep the original ingredient notes above. Add structured records below; no ratios are requested.','ऊपर मूल विवरण रखें। नीचे संरचित रिकॉर्ड जोड़ें; अनुपात आवश्यक नहीं हैं।')}</p>{rows.map(row=><div className="ingredient-row" key={row.id}><div><strong>{row.name}</strong><small>{[row.kind,row.origin,row.sourcing].map(v=>hi?labels[v]||v:v).join(' · ')}</small></div><button type="button" className="button" onClick={()=>{setDraft({...row});setPage(0);setError('')}}>{t('Edit','संपादित करें')}</button><button type="button" className="button" onClick={()=>onChange(rows.filter(r=>r.id!==row.id))}>{t('Remove','हटाएँ')}</button></div>)}
 {!draft?<button type="button" className="button" disabled={rows.length>=20} onClick={()=>{setDraft(blank());setPage(0)}}>{t('Add ingredient','सामग्री जोड़ें')} ({rows.length}/20)</button>:<fieldset><legend>{t('Ingredient record','सामग्री रिकॉर्ड')} · {page+1}/2</legend>{fields.map(([key,en,hindi,options])=><div className="field" key={key}><label htmlFor={`ingredient-${key}`}>{hi?hindi:en}</label>{options?<select id={`ingredient-${key}`} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{hi?labels[v]||v:v}</option>)}</select>:<input id={`ingredient-${key}`} maxLength={160} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</div>)}{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button" onClick={()=>{setDraft(null);setError('')}}>{t('Cancel','रद्द करें')}</button><button type="button" className="button primary" onClick={()=>{if(validateIngredient(draft)){setError(t('Enter a name, or enter Unknown.','नाम दर्ज करें, या Unknown लिखें।'));return}setError('');if(page===0){setPage(1);return}onChange([...rows.filter(r=>r.id!==draft.id),draft]);setDraft(null);setPage(0)}}>{page===0?t('Next','आगे'):t('Save ingredient','सामग्री सहेजें')}</button></div></fieldset>}</div>
}
