import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useApp } from './context'
import Guidance from './MockGuidance'

export default function MockQuestion(){
 const {language}=useApp(),hi=language==='hi',t=(a,b)=>hi?b:a,[params]=useSearchParams()
 const [question,setQuestion]=useState(params.get('q')||''),[jurisdiction,setJurisdiction]=useState('IN'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[submitted,setSubmitted]=useState(null)
 return <div className="page-enter"><div className="page-heading"><div><h1>{t('Start with a question','एक प्रश्न से शुरू करें')}</h1><p>{t('General information does not require a Product Passport.','सामान्य जानकारी के लिए उत्पाद पासपोर्ट आवश्यक नहीं है।')}</p></div></div><div className="notice">{t('MOCK API. Information, not legal advice. Do not enter confidential information.','कृत्रिम API। जानकारी के लिए, कानूनी सलाह नहीं। गोपनीय जानकारी दर्ज न करें।')}</div><form className="panel" onSubmit={e=>{e.preventDefault();setSubmitted({id:'general-question',general:true,confirmed:true,jurisdiction,asOf:date,facts:{question},versions:[]})}}><div className="jurisdiction-control"><label>{t('Jurisdiction','अधिकार क्षेत्र')}<select value={jurisdiction} onChange={e=>{setSubmitted(null);setJurisdiction(e.target.value)}}><option value="IN">India / भारत</option><option value="TREATY">Treaty framework / संधि</option><option value="US">United States</option><option value="EU">European Union</option></select></label><label>{t('As of','तिथि')}<input required type="date" value={date} onChange={e=>{setSubmitted(null);setDate(e.target.value)}}/></label></div><div className="field"><label htmlFor="question">{t('Your question','आपका प्रश्न')}</label><textarea id="question" required maxLength={3000} value={question} onChange={e=>{setSubmitted(null);setQuestion(e.target.value)}}/></div><button className="button primary" disabled={!question.trim()}>{t('Prepare mock question','कृत्रिम प्रश्न तैयार करें')}</button></form>{submitted&&<><div className="panel" style={{marginTop:20}}><h2>{t('Original question','मूल प्रश्न')}</h2><p>{submitted.facts.question}</p><small>{t('Normalization/translation not performed by this mock.','इस परीक्षण में सामान्यीकरण/अनुवाद नहीं हुआ है।')}</small></div><Guidance key={JSON.stringify(submitted)} item={submitted}/></>}</div>
}
