import { useState, useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import { useApp } from './context'
import { prepareEscalation } from './mockApi'

export default function MockReview({item}){
 const {language,updateCase}=useApp(),hi=language==='hi',t=(a,b)=>hi?b:a
 const [consent,setConsent]=useState(false),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const controller=useRef(null)
 useEffect(()=>()=>controller.current?.abort(),[])
 async function send(){controller.current?.abort();controller.current=new AbortController();setBusy(true);setError('');try{const sharing=await prepareEscalation(item,question,consent,controller.current.signal);updateCase(item.id,{sharing,status:'Under human review'})}catch(e){if(e.name!=='AbortError')setError(e.message)}finally{if(!controller.current.signal.aborted)setBusy(false)}}
 return <div className="panel"><h2>{t('Mock facilitator handoff','कृत्रिम विशेषज्ञ समीक्षा')}</h2><div className="notice">{t('Local simulation only. No case is delivered to a real person.','केवल स्थानीय परीक्षण। केस किसी वास्तविक व्यक्ति को नहीं भेजा जाता।')}</div><div className="field"><label htmlFor="review-question">{t('Question for the reviewer','समीक्षक के लिए प्रश्न')}</label><textarea id="review-question" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)}/></div><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t('Include my current facts and question in a local mock review packet.','वर्तमान तथ्यों और प्रश्न को स्थानीय परीक्षण पैकेट में शामिल करें।')}</label><button className="button primary" disabled={busy||!consent||!question.trim()} onClick={send}>{busy?t('Preparing…','तैयार हो रहा है…'):t('Submit to mock queue','कृत्रिम सूची में भेजें')}</button>{error&&<p role="alert">{error}</p>}{item.sharing&&<><p className="notice">MOCK · {item.status} · {t('External delivery: not sent','बाहरी वितरण: नहीं भेजा गया')}</p><button className="button" onClick={()=>updateCase(item.id,{status:'Reviewed',sharing:{...item.sharing,status:'Reviewed',comments:[{at:new Date().toISOString(),author:'Synthetic reviewer',text:'MOCK COMMENT: Confirm ingredient origin and consult a qualified facilitator. No legal opinion provided.'}]}})}>{t('Simulate reviewer response','समीक्षक प्रतिक्रिया का परीक्षण')}</button><button className="button" onClick={()=>{updateCase(item.id,{sharing:null,status:'Guidance ready'});setConsent(false)}}>{t('Withdraw mock sharing','कृत्रिम साझाकरण वापस लें')}</button>{item.sharing.comments?.map(c=><blockquote key={c.at}>{c.text}</blockquote>)}<Link className="button" to={`/cases/${item.id}/export`}>{t('Export packet','पैकेट निर्यात करें')}</Link></>}</div>
}
