import Localized from './Localized'
import { useState, useEffect } from 'react'
import { Link, NavLink, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { useQuery } from '@tanstack/react-query'
import { Plus, ArrowRight, ArrowUpRight, Leaf, FolderOpen, Search, Globe2, ShieldCheck, CircleHelp, BookOpen, Download, FileJson, Printer, AlertTriangle, ExternalLink, LoaderCircle, Trash2, LockKeyhole, Scale, FlaskConical } from 'lucide-react'
import { useApp, makeCase } from './context'
import { missingFacts, exportPayload, exportHtml, downloadFile } from './domain'
import { sources } from './data'
import Modal from './components/Modal'
import Passport from './Passport'
import Guidance from './MockGuidance'
import Review from './MockReview'
import CaseHistory from './CaseHistory'

function Heading({eyebrow,title,body,children}){return <Localized><div className="page-heading"><div className="page-title"><div className="eyebrow">{eyebrow||'AYUNEX WORKSPACE'}</div><h1 data-original>{title}</h1>{body&&<p>{body}</p>}</div>{children}</div></Localized>}
function DemoNotice(){return <Localized><div className="notice"><FlaskConical size={18}/><span><strong>Session-only demonstration.</strong> Changes stay in memory and reset when this page reloads. Do not enter personal secrets or confidential formulations.</span></div></Localized>}
function ContextControls({value,date,onChange,onDate}){return <Localized><div className="jurisdiction-control"><Globe2 size={19}/><label>Jurisdiction<select value={value} onChange={e=>onChange(e.target.value)}><option value="IN">India</option><option value="TREATY">International · treaty framework</option><option value="US">International · United States</option><option value="EU">International · European Union</option></select></label><label>As of<input type="date" required value={date} onChange={e=>{if(e.target.value)onDate(e.target.value)}}/></label><small>Language does not change jurisdiction.</small></div></Localized>}

export function NewCase(){
 const {setCases,setConsent,language,backendMode,backendClient,notify}=useApp(),navigate=useNavigate(),hi=language==='hi'
 const [busy,setBusy]=useState(false)
 const schema=z.object({title:z.string().trim().min(3,'Use at least 3 characters.').max(90,'Keep the title under 90 characters.'),jurisdiction:z.string(),consent:z.literal(true,{error:'Please acknowledge the session-only demo notice.'})})
 const {register,handleSubmit,formState:{errors}}=useForm({resolver:zodResolver(schema),defaultValues:{title:'',jurisdiction:'IN',consent:false}})
 async function submit(v){
  if(backendMode==='live'&&backendClient){
   try{
    setBusy(true)
    const jur=v.jurisdiction==='IN'?{layer:'NATIONAL',country:'IN',framework:null}
      :v.jurisdiction==='TREATY'?{layer:'TREATY_FRAMEWORK',country:null,framework:'PCT'}
      :{layer:'EXPORT_MARKET',country:v.jurisdiction,framework:null}
    const created=await backendClient.createCase({
     title:v.title,
     query_kind:'PRODUCT_SPECIFIC',
     jurisdiction:jur,
     as_of_date:new Date().toISOString().slice(0,10),
     consent:{accepted:true,notice_version:'case-notice-v1'}
    })
    const c={id:created.id,title:created.title,sample:false,status:created.status,jurisdiction:v.jurisdiction,asOf:created.as_of_date,facts:{name:created.title},revision:created.revision,passportVersion:created.passport_version,confirmed:false,completed:[],versions:[],live:true}
    setCases(old=>[c,...old]);setConsent(true);notify(hi?'केस सफलतापूर्वक बनाया गया':'Case created on live backend');navigate(`/cases/${c.id}/passport`)
    return
   }catch(err){notify(err.message||'Failed to create case on server');setBusy(false);return}
  }
  const c=makeCase(v.title,v.jurisdiction);c.consent={version:'demo-notice-1',at:new Date().toISOString(),purpose:'session-only case'};setCases(old=>[c,...old]);setConsent(true);navigate(`/cases/${c.id}/passport`)
 }
 return <Localized><div className="page-enter"><Heading title={hi?'आपके अगले विचार के लिए एक जगह':'A home for your next idea'} body="Start with a name. We’ll ask the relevant questions along the way."/><div className="two-column"><form className="panel" onSubmit={handleSubmit(submit)}><div className="wizard-heading"><span className="feature-icon"><Leaf size={24}/></span><div><h2>{hi?'नया उत्पाद केस':'Create a product case'}</h2><p>{backendMode==='live'?(hi?'लाइव बैकएंड मोड सक्रिय':'Live FastAPI connected'):'No exact formulation ratios needed.'}</p></div></div><div className="field"><label htmlFor="case-name">{hi?'केस का नाम':'Case name'}</label><input id="case-name" disabled={busy} placeholder="e.g. Botanical skincare concept" {...register('title')}/>{errors.title&&<span className="error">{errors.title.message}</span>}</div><div className="field"><label htmlFor="case-jurisdiction">{hi?'प्रारंभिक अधिकार क्षेत्र':'Starting jurisdiction'}</label><select id="case-jurisdiction" disabled={busy} {...register('jurisdiction')}><option value="IN">India</option><option value="TREATY">International treaty framework</option><option value="US">United States</option><option value="EU">European Union</option></select></div><DemoNotice/><label className="check-label"><input type="checkbox" disabled={busy} {...register('consent')}/><span>I understand this is a research and preparation platform, provides information rather than legal advice, and will not guarantee legal outcome.</span></label>{errors.consent&&<p className="error">{errors.consent.message}</p>}<div className="form-actions"><Link className="button" to="/">Cancel</Link><button className="button primary" disabled={busy} type="submit">{busy?(hi?'बनाया जा रहा है…':'Creating…'):hi?'पासपोर्ट शुरू करें':'Start Product Passport'}<ArrowRight size={17}/></button></div></form><aside className="panel"><div className="eyebrow">WHAT HAPPENS NEXT</div><h2>One case. Separate questions.</h2><ul className="stepper"><li><span>1</span>Describe the product and its intended use</li><li><span>2</span>Confirm the facts that affect the route</li><li><span>3</span>Review regulatory, IP and ABS issues separately</li><li><span>4</span>Keep a traceable case file</li></ul><div className="notice"><CircleHelp size={18}/><span>Only have a general question? You don’t need to create a case.</span></div><Link to="/ask" className="text-link">Ask a general question <ArrowUpRight size={16}/></Link></aside></div></div></Localized>
}
export function CaseList(){const {cases}=useApp(),[search,setSearch]=useState(''),[filter,setFilter]=useState('All');const filtered=cases.filter(c=>c.title.toLowerCase().includes(search.toLowerCase())&&(filter==='All'||c.status===filter));return <Localized><div className="page-enter"><Heading title="Your case desk" body="Keep product facts and the questions still to resolve together."><Link to="/cases/new" className="button primary"><Plus size={17}/>New case</Link></Heading><div className="toolbar"><Search size={19}/><input aria-label="Search cases" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a case…"/><select aria-label="Filter cases" value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Draft','Needs information','Guidance preview','Guidance ready','Under human review','Reviewed','Review prepared','Archived'].map(v=><option key={v}>{v}</option>)}</select></div><div className="panel">{filtered.map(c=><Link to={`/cases/${c.id}/passport`} className="case-row" key={c.id}><div className="case-avatar"><Leaf size={21}/></div><div className="case-row-title"><strong data-original>{c.title}</strong><small>{c.id} · {c.live?'Live server':c.sample?'Synthetic sample':'Session only'} · {c.jurisdiction}</small></div><span className="status">{c.status}</span><ArrowUpRight size={18}/></Link>)}{!filtered.length&&<div className="empty-state"><FolderOpen size={35}/><h2>No matching cases</h2><p>Try another search or create a new case.</p></div>}</div><DemoNotice/></div></Localized>}

function Assessment({item}){
 const {updateCase,notify,backendMode,backendClient,language}=useApp(),missing=missingFacts(item.facts),navigate=useNavigate(),hi=language==='hi'
 const [classifying,setClassifying]=useState(false),[liveResult,setLiveResult]=useState(null),[liveClarify,setLiveClarify]=useState(null)
 async function runLiveClassify(){
  if(!backendClient||!item.id)return
  try{
   setClassifying(true)
   const cRes=await backendClient.classify(item.id)
   setLiveResult(cRes.payload||cRes)
   const qRes=await backendClient.clarify(item.id)
   setLiveClarify(qRes.payload||qRes)
   notify(hi?'लाइव वर्गीकरण संपन्न हुआ':'Statutory classification evaluated')
  }catch(e){notify(e.message||'Classification error')}
  finally{setClassifying(false)}
 }
 return <Localized><><div className="panel"><div className="section-heading"><h2>Confirm your product facts</h2><span className="status">PROVISIONAL · UNRESOLVED</span></div><div className="fact-grid">{Object.entries(item.facts).map(([k,v])=><div key={k}><small>{k.replaceAll('_',' ')}</small><span data-original>{Array.isArray(v)?v.map(row=>[row.name,row.part,row.kind,row.origin,row.sourcing].filter(Boolean).join(' · ')).join('; '):v||'Unknown'}</span></div>)}</div><label className="check-label"><input type="checkbox" checked={item.confirmed} onChange={e=>updateCase(item.id,{confirmed:e.target.checked})}/><span>I have reviewed these facts. This confirms my input, not a legal classification.</span></label><div className="form-actions"><Link className="button" to={`/cases/${item.id}/passport`}>Edit facts</Link>{backendMode==='live'&&backendClient&&<button type="button" className="button" disabled={classifying} onClick={runLiveClassify}><FlaskConical size={16}/>{classifying?(hi?'जाँच जारी…':'Evaluating…'):(hi?'वैधानिक वर्गीकरण चलाएँ':'Run statutory classification')}</button>}<button className="button primary" disabled={!item.confirmed} onClick={()=>{updateCase(item.id,{status:'Guidance preview',assessment:{support:missing.length?'MISSING_FACTS':'MISSING_EVIDENCE'},versions:[...item.versions,{id:item.versions.length+1,at:new Date().toISOString(),jurisdiction:item.jurisdiction,asOf:item.asOf,facts:{...item.facts},support:'MISSING_EVIDENCE'}]});notify('Example guidance view prepared. No live legal assessment was performed.');navigate(`/cases/${item.id}/guidance`)}}>Open guidance preview <ArrowRight size={16}/></button></div></div>
 {liveResult&&<div className="panel" style={{borderLeft:'3px solid #d4af37'}}><div className="section-heading"><h2>{hi?'वैधानिक निर्णय परिणाम':'Statutory Decision Results'}</h2><span className="code-label">{liveResult.ruleset_version} · {liveResult.route}</span></div><p>{liveResult.reasons?.join('. ')}</p><h3>{hi?'संभावित उम्मीदवार मार्ग':'Candidate Route Alternatives'}</h3><div className="action-grid">{liveResult.alternatives?.map(a=><div key={a.route} className="panel" style={{padding:16}}><strong>{a.route}</strong><small style={{display:'block',color:'#aaa'}}>Conditions met: {a.all_conditions_met?'YES':'PENDING'}</small>{a.conditions.map(c=><div key={c.fact_id} className="condition">{c.fact_id}<span>{c.state}</span></div>)}</div>)}</div>{liveClarify?.questions?.length>0&&<div style={{marginTop:18}}><h3>{hi?'मार्ग स्पष्ट करने हेतु प्रश्न':'Prioritized Clarifying Questions'}</h3>{liveClarify.questions.map(q=><div key={q.fact_id} className="notice" style={{marginTop:8}}><strong>{hi?q.text_hi:q.text}</strong><small style={{display:'block',color:'#888'}}>{q.reason}</small></div>)}</div>}</div>}
 <div className="notice"><AlertTriangle size={18}/><span>{missing.length?`Missing decisive facts: ${missing.join(', ')}.`:'Facts recorded.'} {backendMode==='live'?'Statutory classification rules available above.':'The legal rules service is not connected. No category, patentability or ABS clearance is inferred.'}</span></div><div className="assessment-grid">{[['Regulatory route',FlaskConical,'Classical, proprietary, new-drug, phytopharmaceutical, food and cosmetic routes need separate eligibility checks.'],['IP opportunities',FingerprintIcon,'A product category does not establish patentability. Prior art and other rights need separate assessment.'],['ABS checkpoints',Leaf,'Applicant, activity, origin and exceptions must be reviewed independently.']].map(([title,Icon,body])=><div className="panel" key={title}><Icon size={26}/><h3>{title}</h3><span className="status">MISSING_EVIDENCE</span><p>{body}</p><div className="condition">Rule conditions <span>Unknown</span></div><div className="condition">Reviewed ruleset <span>{backendMode==='live'?'Live ayunex-0.1.0':'Not connected'}</span></div></div>)}</div></></Localized>
}
function FingerprintIcon(props){return <ShieldCheck {...props}/>}
function Evidence({item}){const [selected,setSelected]=useState(null);return <Localized><><Heading title="Evidence you can inspect" body="No source passages have been retrieved for this case. These are official starting points, not citations supporting an answer."/><div className="source-grid">{sources.filter(s=>s.jurisdiction===(item.jurisdiction==='IN'?'IN':'INTERNATIONAL')).map(s=><div className="panel source-card" key={s.id}><BookOpen size={25}/><span className="tag"> {s.jurisdiction} · OFFICIAL POINTER</span><h3>{s.title}</h3><p>{s.description}</p><button className="button" onClick={()=>setSelected(s)}>Inspect source metadata <ArrowUpRight size={15}/></button></div>)}</div>{selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><div className="fact-grid">{Object.entries({Authority:selected.authority,Jurisdiction:selected.jurisdiction,'Provision ID':'Not retrieved','Effective interval':'Unknown','Source version':'Not ingested','Review status':'Not reviewed','Retrieved at':'Not retrieved','As-of context':item.asOf}).map(([k,v])=><div key={k}><small>{k}</small>{v}</div>)}</div><div className="notice">No authoritative excerpt is available. The live evidence service must supply an exact original passage and locator.</div><a href={selected.url} target="_blank" rel="noreferrer" className="button primary">Open official source <ExternalLink size={15}/></a></Modal>}</></Localized>}
const tasks=['Confirm intended use and claims','Identify formula / authoritative text reference','Record ingredient identity and origin','Discuss unresolved issues with an IP facilitator']
function ExportCase({item}){const {updateCase,backendMode,backendClient,notify,language}=useApp(),hi=language==='hi';return <Localized><div className="panel"><h2>Your case file</h2><p>Includes recorded facts, missing information, jurisdiction, timestamps and the explicit demo disclaimer. No unverified citations are added.</p><div className="export-grid"><button onClick={()=>downloadFile(JSON.stringify(exportPayload(item),null,2),`${item.id}.json`,'application/json')}><FileJson size={27}/><strong>Export JSON</strong><small>Structured case data</small></button><button onClick={()=>downloadFile(exportHtml(item),`${item.id}.html`,'text/html')}><Download size={27}/><strong>Export HTML</strong><small>Readable case report</small></button><button onClick={()=>{const w=window.open('','_blank');if(w){w.document.write(exportHtml(item));w.document.close();w.focus();w.print()}}}><Printer size={27}/><strong>Print / save PDF</strong><small>Use your browser’s PDF printer</small></button>{backendMode==='live'&&backendClient&&<button onClick={async()=>{try{const r=await backendClient.exportCase(item.id);notify(hi?'सर्वर निर्यात आर्टिफ़ैक्ट दर्ज हुआ':'Server export artifact recorded');downloadFile(JSON.stringify(r.payload,null,2),`ayunex-${item.id}.json`,'application/json')}catch(e){notify(e.message)}}}><FileJson size={27}/><strong>{hi?'सर्वर JSON':'Server JSON'}</strong><small>Verified server artifact</small></button>}</div><h3>Preparation checklist</h3>{tasks.map((t,i)=><label className="check-label" key={t}><input type="checkbox" checked={item.completed.includes(i)} onChange={e=>updateCase(item.id,{completed:e.target.checked?[...item.completed,i]:item.completed.filter(n=>n!==i)})}/>{t}</label>)}<CaseHistory item={item}/><h3 style={{marginTop:25}}>Session versions</h3>{item.versions.length?item.versions.map((v,i)=><div className="condition" key={v.id}>Preview {i+1}<span>{v.jurisdiction} · {new Date(v.at).toLocaleString()}</span></div>):<p>No guidance previews recorded yet.</p>}</div></Localized>}
export function Workspace(){const {id,section='passport'}=useParams(),{cases,updateCase,notify}=useApp(),item=cases.find(c=>c.id===id);if(!item)return <Localized><div className="empty-state"><FolderOpen size={36}/><h1>This case isn’t in your session</h1><p>Session-only cases reset after a page reload.</p><Link to="/cases/new" className="button primary">Create a case</Link></div></Localized>;const tabs=[['passport','Product Passport'],['classification','Assessments'],['guidance','Guidance'],['evidence','Evidence'],['export','Case file'],['review','Human review']];return <Localized><div className="page-enter"><Heading eyebrow={`${item.id.toUpperCase()} · ${item.live?'LIVE SERVER CASE':item.sample?'SYNTHETIC SAMPLE':'SESSION-ONLY CASE'}`} originalTitle title={item.title} body="Your product facts, evidence and unresolved questions."><span className="status">{item.status}</span></Heading><ContextControls value={item.jurisdiction} date={item.asOf} onChange={v=>{updateCase(id,{jurisdiction:v},true);notify('Context changed. Previous assessments have been invalidated.')}} onDate={v=>{updateCase(id,{asOf:v},true);notify('As-of date changed. Review is required again.')}}/><nav className="tabs" aria-label="Case sections">{tabs.map(([url,label])=><NavLink key={url} to={`/cases/${id}/${url}`}>{label}</NavLink>)}</nav>{section==='passport'?<Passport key={id} item={item}/>:section==='classification'?<Assessment item={item}/>:section==='guidance'?<Guidance key={`${id}-${item.jurisdiction}-${item.asOf}-${JSON.stringify(item.facts)}`} item={item}/>:section==='evidence'?<Evidence key={`${id}-${item.jurisdiction}`} item={item}/>:section==='export'?<ExportCase item={item}/>:section==='review'?<Review key={`${id}-${item.jurisdiction}-${item.asOf}-${JSON.stringify(item.facts)}`} item={item}/>:<div className="notice">Unknown section. Choose a tab above.</div>}<DemoNotice/></div></Localized>}

export function Sources(){const [params,setParams]=useSearchParams(),search=params.get('q')||'',setSearch=value=>setParams(value?{q:value}:{}),[filter,setFilter]=useState('All');const {data=[],isPending}=useQuery({queryKey:['source-directory'],queryFn:async()=>sources,staleTime:Infinity});const visible=data.filter(s=>(s.title+' '+s.description+' '+s.authority).toLowerCase().includes(search.toLowerCase())&&(filter==='All'||s.domain===filter));return <Localized><div className="page-enter"><Heading title="The knowledge base" body="Official starting points for your research. This directory does not imply a current, ingested or verified legal corpus."/><div className="toolbar"><Search size={19}/><input aria-label="Search knowledge base" placeholder="Search statutes, authorities or topics…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter source domain" value={filter} onChange={e=>setFilter(e.target.value)}>{['All','IP','Regulatory','ABS','TK'].map(v=><option key={v}>{v}</option>)}</select></div>{isPending?<div className="loading-row"><LoaderCircle className="spin"/>Loading directory</div>:<div className="source-grid">{visible.map(s=><article className="panel source-card" key={s.id}><BookOpen size={24}/><span className="tag"> {s.domain.toUpperCase()} · {s.jurisdiction}</span><h3>{s.title}</h3><p>{s.description}</p><a className="text-link" href={s.url} target="_blank" rel="noreferrer">Open official source <ExternalLink size={15}/></a></article>)}</div>}{!visible.length&&<div className="empty-state"><Search size={30}/><h2>No matching sources</h2><p>Try a broader term or another domain.</p></div>}</div></Localized>}
export function Preferences(){const {language,setLanguage,motion,setMotion,cases,setCases,notify,consent,setConsent}=useApp(),[deleting,setDeleting]=useState(false);return <Localized><div className="page-enter"><Heading title="Make the workspace yours" body="Language, motion and your session’s privacy controls."/><div className="panel"><div className="settings-row"><div><h3>Interface language</h3><p>English and Hindi navigation. Legal source text stays in its original language.</p></div><select aria-label="Interface language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="hi">हिन्दी</option></select></div><div className="settings-row"><div><h3>3D and motion</h3><p>Pause the globe and interface animations. Reduced-motion preference is respected.</p></div><button role="switch" aria-checked={motion} aria-label="Enable animation" className={`toggle ${motion?'on':''}`} onClick={()=>setMotion(!motion)}><span/></button></div><div className="settings-row"><div><h3>Case data</h3><p>{cases.length} cases in this browser tab’s memory. Only your language preference uses local storage.</p></div><button className="button" onClick={()=>downloadFile(JSON.stringify(cases.map(exportPayload),null,2),'ip-sakti-session.json','application/json')}><Download size={16}/>Export</button></div><div className="settings-row"><div><h3>Session consent</h3><p>{consent?'Acknowledged for session-only cases.':'No new-case consent recorded.'} Voice and facilitator sharing require separate choices.</p></div><button className="button" onClick={()=>{setConsent(false);setCases(old=>old.map(c=>({...c,sharing:null})));notify('Session consent withdrawn. Existing data remains until you delete it.')}}>Withdraw</button></div><div className="settings-row"><div><h3>Delete this session’s cases</h3><p>Removes sample and newly created cases from memory. This cannot be undone.</p></div><button className="button danger" onClick={()=>setDeleting(true)}><Trash2 size={16}/>Delete all</button></div></div>{deleting&&<Modal title="Delete all session cases?" onClose={()=>setDeleting(false)}><p>Export anything you want to keep first. All cases and prepared handoff packets in this session will be removed.</p><div className="form-actions"><button className="button" onClick={()=>setDeleting(false)}>Cancel</button><button className="button danger" onClick={()=>{setCases([]);setConsent(false);setDeleting(false);notify('All session case data removed.')}}>Delete session data</button></div></Modal>}</div></Localized>}
export function Information({privacy=false,login=false}){return <Localized><div className="page-enter"><Heading title={privacy?'Privacy, by design':login?'Your private workspace':'A considered workspace for Ayurveda innovation'} body="AYUNEX · Team AYUNEX · SIH 26045"/><div className="panel"><ShieldCheck size={30}/><h2 style={{marginTop:18}}>{login?'Guest demonstration only':'Know what this frontend can do'}</h2><p>This is a React and JavaScript implementation of the frontend experience. Product Passport editing, case context, source discovery, export and handoff preparation work locally. Email-verified sign-in, saved cases and source-grounded queries are connected to the backend. Demo screens remain labelled; legal rules and corpus coverage still require expert validation.</p><div className="notice">Use synthetic or non-confidential information only. The demonstration does not provide legal advice, regulatory approvals or patentability decisions.</div><div className="section-list">{[['Your case data','Demo cases live in this tab’s memory. Signed-in live cases are stored by the backend and linked to your account. Exported files remain on your device until you delete them. Language preference is the only app value stored in local storage.'],['Third-party connections','When you explicitly consent, live questions and retrieved source excerpts are sent through the backend to the configured AI provider. Without that consent, hosted processing is disabled. The interface requests Google Fonts and opening official links contacts those websites. The 3D scene runs on your device.'],['Language and accessibility','English and Hindi interfaces are available. Original source text, user-entered facts and technical identifiers are preserved. Independent bilingual legal validation is required before production.'],['Evidence and uncertainty','All example assessments remain unresolved. A support-state preview is a visual test, not an evidence-backed answer. Official directory links do not mean those documents have been retrieved or verified.'],['What comes next','Complete expert-reviewed legal coverage, multilingual acceptance, live facilitator delivery and deployment security/backup testing before public release.']].map(([t,b])=><details key={t}><summary>{t}</summary><p>{b}</p></details>)}</div><div className="privacy-links"><Link to="/settings" className="button">Privacy controls</Link><Link to="/" className="button primary">Continue as guest</Link></div></div></div></Localized>}
export function Facilitators(){
 const {cases,backendMode,backendClient,language}=useApp(),hi=language==='hi',t=(a,b)=>hi?b:a
 const [liveQueue,setLiveQueue]=useState([])
 const [loading,setLoading]=useState(false)

 useEffect(()=>{
  let active = true
  if(backendMode==='live'&&backendClient){
   const timer = setTimeout(() => {
    if(active) setLoading(true)
   }, 0)
   backendClient.queue()
    .then(q=>{ if(active) setLiveQueue(q||[]) })
    .catch(()=>{ if(active) setLiveQueue([]) })
    .finally(()=>{ if(active) setLoading(false) })
   return () => {
    active = false
    clearTimeout(timer)
   }
  }
 },[backendMode,backendClient])

 const prepared=cases.filter(c=>c.sharing)

 return <Localized><div className="page-enter"><Heading title="Facilitator desk" body={backendMode==='live'?'Live reviewer queue from Module B.':'Prepared handoffs in this session. No requests have been delivered to real facilitators.'}/><div className="notice"><LockKeyhole size={18}/>{backendMode==='live'?'Live Module B escalation queue. Reviews are recorded with actor and timestamp.':'Demo queue only. A production queue requires verified reviewer identity, access controls and consent enforcement.'}</div>
 {backendMode==='live'?(
  <div className="panel">
   <h2>{t('Module B Live Escalation Queue','मॉड्यूल B लाइव समीक्षा कतार')}</h2>
   {loading?<p>Loading queue…</p>:liveQueue.length?liveQueue.map(item=>(
    <div key={item.id} className="case-row" style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
     <div>
      <strong>{item.payload?.question||'Case Escalation'}</strong>
      <small style={{display:'block',color:'#aaa'}}>ID: {item.id} · Scope: {item.payload?.scope} · Status: {item.payload?.status}</small>
     </div>
     <Link to={`/cases/${item.payload?.case_id || item.id}/review`} className="button">{t('Inspect Packet','पैकेट देखें')}</Link>
    </div>
   )):<div className="empty-state"><Scale size={35}/><h2>{t('No pending escalations','कोई लंबित समीक्षा नहीं')}</h2><p>{t('Cases submitted with facilitator sharing consent will appear here.','साझाकरण सहमति वाले केस यहाँ दिखेंगे।')}</p></div>}
  </div>
 ):(
  <div className="panel">{prepared.length?prepared.map(c=><Link className="case-row" to={`/cases/${c.id}/review`} key={c.id}><Scale size={23}/><div className="case-row-title"><strong data-original>{c.title}</strong><small>Prepared locally · not sent</small></div><ArrowUpRight size={18}/></Link>):<div className="empty-state"><Scale size={35}/><h2>No prepared handoffs</h2><p>Open a case’s Human review tab to prepare one.</p><Link to="/cases" className="button primary">Open case desk</Link></div>}</div>
 )}
 </div></Localized>
}
