import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { Mic } from 'lucide-react'
import { useApp } from './context'
import { applicableSteps, ingredientSummary } from './passportRules'
import IngredientEditor from './IngredientEditor'
import VoiceInputModal from './components/VoiceInputModal'
import { progressFor } from './domain'

const optionHi={'Oral':'मुख से','External':'बाहरी प्रयोग','Ayurveda Aahara':'आयुर्वेद आहार','Other food / nutraceutical':'अन्य खाद्य / न्यूट्रास्यूटिकल','Therapeutic':'चिकित्सीय','Food':'खाद्य','Cosmetic':'प्रसाधन','Research':'अनुसंधान','Unknown':'मुझे नहीं पता','Capsule':'कैप्सूल','Powder':'चूर्ण','Liquid':'तरल','Topical':'बाहरी उपयोग','Other':'अन्य','India':'भारत','Outside India':'भारत के बाहर','Mixed':'मिश्रित','Text reference only':'केवल ग्रंथ संदर्भ','Quality testing':'गुणवत्ता परीक्षण','Safety / efficacy studies':'सुरक्षा / प्रभावशीलता अध्ययन','None yet':'अभी नहीं','Individual':'व्यक्ति','Indian organisation':'भारतीय संस्था','Foreign organisation':'विदेशी संस्था','Prototype':'प्रारूप','Preparing launch':'बाजार की तैयारी','Commercial':'व्यावसायिक','United States':'संयुक्त राज्य अमेरिका','European Union':'यूरोपीय संघ','Not disclosed':'प्रकाशित नहीं','Published / shared publicly':'सार्वजनिक रूप से साझा','Application filed':'आवेदन दर्ज'}
export default function Passport({item}){
 const {language,updateCase,notify,backendMode}=useApp(),hi=language==='hi',t=(a,b)=>hi?b:a,navigate=useNavigate()
 const [index,setIndex]=useState(0),[file,setFile]=useState(''),[fileError,setFileError]=useState('')
 const [voiceField,setVoiceField]=useState(null)
 const groups=applicableSteps(item.facts),group=groups[index]
 const {register,handleSubmit,setValue,getValues,formState:{errors}}=useForm({values:item.facts,mode:'onBlur'})
 function save(values){if(JSON.stringify(values)!==JSON.stringify(item.facts))updateCase(item.id,{facts:values},true)}
 function next(values){save(values);if(index<groups.length-1)setIndex(index+1);else navigate(`/cases/${item.id}/classification`)}
 const isLive = item.live || backendMode === 'live'

 return <div className="two-column"><form className="panel" onSubmit={handleSubmit(next)}><span className="code-label">{isLive?t('LIVE BACKEND SYNC','लाइव बैकएंड सिंक'):t('PRODUCT PASSPORT','उत्पाद पासपोर्ट')} · {index+1}/{groups.length}</span><h2>{hi?group.hi:group.name}</h2><p className="passport-reason">{hi?group.helpHi:group.help}</p>
 {group.fields.map(([key,en,hindi,options])=><div className="field" key={key}><label htmlFor={`fact-${key}`}>{hi?hindi:en} <small>({['use','form','source','ingredients','origin'].includes(key)?t('needed for assessment','आकलन के लिए आवश्यक'):t('optional','वैकल्पिक')})</small></label>{options?<select id={`fact-${key}`} {...register(key,{required:['use','form','origin'].includes(key)?t('Choose an option or Unknown.','विकल्प या “मुझे नहीं पता” चुनें।'):false,onChange:e=>save({...getValues(),[key]:e.target.value})})}><option value="">{t('Select','चुनें')}</option>{options.map(o=><option key={o} value={o}>{hi?optionHi[o]||o:o}</option>)}</select>:<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:4}}><button type="button" className="text-link" style={{background:'none',fontSize:12,display:'flex',alignItems:'center',gap:4}} onClick={()=>setVoiceField({key,label:hi?hindi:en})}><Mic size={13}/>{t('Speak to enter','बोलकर दर्ज करें')}</button><button type="button" className="text-link" style={{background:'none',fontSize:12}} onClick={()=>{setValue(key,'Unknown',{shouldValidate:true});save(getValues())}}>{t('I do not know','मुझे नहीं पता')}</button></div><textarea id={`fact-${key}`} {...register(key,{maxLength:{value:1500,message:t('Maximum 1500 characters.','अधिकतम 1500 अक्षर।')},validate:v=>!v||v.trim().length>0||t('Enter a value or choose Unknown.','तथ्य दर्ज करें या अज्ञात चुनें।'),onBlur:()=>save(getValues())})}/></>}{errors[key]&&<span className="error" role="alert">{errors[key].message}</span>}<small>{t('Provenance: user-entered. Unknown facts remain unresolved.','स्रोत: उपयोगकर्ता। अज्ञात तथ्य अनिर्णीत रहते हैं।')}</small></div>)}
 {group.name==='Source & ingredients'&&<IngredientEditor rows={item.facts.ingredientRows||[]} onChange={rows=>{setValue('ingredientRows',rows);if(!getValues('ingredients')||getValues('ingredients')==='Unknown')setValue('ingredients',ingredientSummary(rows)||'Unknown');save(getValues())}}/>}
 {group.name==='Process & evidence'&&<div className="field"><label htmlFor="evidence-file">{t('Evidence file (metadata only)','प्रमाण फ़ाइल (विवरण)')}</label><input id="evidence-file" type="file" accept=".pdf,.txt" onChange={e=>{const f=e.target.files?.[0];setFileError('');if(!f)return;if(f.size>5*1024*1024||!(/\.(pdf|txt)$/i.test(f.name))){setFileError(t('Use PDF/TXT, maximum 5 MB.','PDF/TXT, अधिकतम 5 MB।'));e.target.value='';return}setFile(f.name);updateCase(item.id,{evidenceFiles:[{name:f.name,size:f.size,type:f.type,uploaded:false}]},true);notify(t('Filename recorded. Contents were not read or uploaded.','नाम दर्ज हुआ। फ़ाइल पढ़ी या अपलोड नहीं हुई।'))}}/><small>{file||t('No file uploaded.','कोई फ़ाइल अपलोड नहीं हुई।')}</small>{fileError&&<span className="error" role="alert">{fileError}</span>}</div>}

 <div className="form-actions"><button type="button" className="button" disabled={!index} onClick={handleSubmit(v=>{save(v);setIndex(index-1)})}>{t('Back','पीछे')}</button><button className="button primary" type="submit">{index===groups.length-1?t('Review facts','तथ्य देखें'):t('Continue','आगे')}</button></div></form>
 <aside className="panel"><h2>{t('Product Passport','उत्पाद पासपोर्ट')}</h2><p>{progressFor(item.facts)}% {t('known fields — not legal confidence','ज्ञात तथ्य — कानूनी विश्वास का माप नहीं')}</p><ul className="stepper">{groups.map((g,i)=><li key={g.name} className={i===index?'active':''}><span>{i+1}</span>{hi?g.hi:g.name}</li>)}</ul><details className="glossary"><summary>{t('Key terms','मुख्य शब्द')}</summary><dl>{[['IP','Intellectual property: rights relating to creations and identifiers.','बौद्धिक संपदा: सृजन और पहचान से जुड़े अधिकार।'],['ABS','Access and benefit-sharing: questions about access to biological resources and sharing benefits.','जैव संसाधनों तक पहुँच और लाभ साझा करने से जुड़े प्रश्न।'],['Prior art','Previously available knowledge considered in an IP review.','बौद्धिक संपदा समीक्षा में विचार किया जाने वाला पूर्व उपलब्ध ज्ञान।']].map(([term,en,hindi])=><div key={term}><dt>{term}</dt><dd>{hi?hindi:en}</dd></div>)}</dl></details><Link to="/ask" className="text-link">{t('General question? Skip the Passport.','सामान्य प्रश्न? पासपोर्ट आवश्यक नहीं।')}</Link></aside>
 {voiceField&&<VoiceInputModal isOpen={Boolean(voiceField)} onClose={()=>setVoiceField(null)} initialLanguage={language} fieldLabel={voiceField.label} onConfirm={text=>{setValue(voiceField.key,text,{shouldValidate:true});save(getValues());notify(t('Voice input applied after confirmation.','पुष्टि के बाद आवाज़ इनपुट लागू हुआ।'))}}/>}
 </div>
}
